### PR TITLE
size condition in UTF-8

### PR DESCRIPTION
**Pull request by kariminf**
1- Add all size conditions in snowball file
2- Fixe string length problem with UTF-8, by
- Adding a new script LENGTH(p) to runtime/header.h; the script allow us to have the number of characters in contrary of SIZE(p) which gives the number of Bytes
- Replacing SIZE(p) with LENGTH(p) in compiler/generator.c to use the length in characters instead of the length in Bytes

Why not modify SIZE(p) directly in runtime/header.h?
Because it is used in compiler/generator.c: wlitarra function, wlitref function, etc. The direct modification may lead to a problem of memory allocation.

### CODE REVIEW

**Comment by assem-ch** [comment]
@kariminf  Here is olly's review comments:

> ({ }) blocks are a GCC extension, so best avoided
> calling setlocale() is really best avoided
> and snowball generated code could be used in many contexts, so calling setlocale() seems a bad idea
> also mbstowcs seems to be C99, which isn't too unreasonable at this point, but it's the first C99 requirement in snowball
> If it needs to be a new C support function, I'd suggest something like: int length_utf8(const symbol \* p, int limit) { int len = 0, c = 0, dummy, r; while ((r = get_utf8(p, c, limit, &dummy)) != 0) { c += r; ++len; } return len; }
> (untested)
> though that presumably requires extending the snowball language, which Martin was never keen on
> he's stepped back, but I think we still want to at least very carefully consider such extensions

So I think we continue using a length function in headers.h until we have a better option

**Comment by kariminf** [comment]
I will try this function, may be it will help:

http://stackoverflow.com/a/5117542/2296914

**Comment by assem-ch** [comment]
Good, he is ok with adding  a `len` funtion to count utf-8 characters:

> [11:17] olly> assem_ch: are you aiming to add something to snowball returning the number of unicode characters?
> [11:19] assem_ch> if we could do it without change in snowball, that's better.. but SIZE gives the right number in java-genrated code but wrong number in C/C++-generated code 
> [11:19] assem_ch> so (size/2) dont work in JAVA
> [11:21] olly> hmm
> [11:22] olly> oh, java works in utf-16
> [11:22] olly> or is it actually UCS-2
> [11:22] olly> i think it isn't wrong, it's just not the number you're after
> [11:23] assem_ch> I dont know , karim is the one testing in java, he said its unicode
> [11:23] assem_ch> SIZE gives the right number in JAVA
> [11:23] assem_ch> but not in C
> [11:23] olly> it's not java vs C really
> [11:23] olly> it's that the java version uses 2-byte uncode
> [11:23] olly> *unicode
> [11:24] olly> and C uses UTF-8
> [11:24] olly> i bet if you built the 2-byte unicode C version it'd give the same answer
> [11:24] assem_ch> how to do it
> [11:24] olly> http://snowball.tartarus.org/compiler/snowman.html section "12 Character representation"
> [11:25] olly> size measures the number of 2 byte characters for the java case
> [11:25] olly> for utf-8, it counts the number of bytes
> [11:25] olly> it just happens that in the java case, size gives the number of characters
> [11:26] olly> but it's not buggy in the utf-8 case, it just isn't the number you want there
> [11:26] olly> this is all a bit confusing, mostly because utf-8 support was added later
> [11:27] olly> i think it's reasonable to provide a way to count the number of unicode characters though
> [11:27] olly> which for the 2-byte unicode case is easy, and for utf-8 has to actually count them
> [11:28] olly> the key part in the manual is " size  and  sizeof  measure string size in slots, not symbols"
> [11:28] olly> and slots are a byte for utf-8
> [11:29] olly> whereas symbols are a variable number of bytes
> [11:32] assem_ch> I understand you are okay of adding a length_utf8 function?
> [11:34] olly> i think just "len" or "length" would make more sense, which for the non-utf8 cases would just return the same number as "size" does
> [11:34] olly> then you can write stemmers which work for all the cases
> [11:36] assem_ch> ok

**Comment by kariminf** [comment]
Hello @assem-ch :
The added length function calculates the bytes that don't start with (01), since all the bytes after the first one must be like (10xxxxxx).

```
int len(const symbol * p)
{
    char * i ;
    int nbrChar = 0;

    for (i = p; *i; i++){
        if ((*i & 0xc0) != 0x80) nbrChar++;
    }

    return nbrChar;
}
```

https://en.wikipedia.org/wiki/UTF-8

**Comment by assem-ch** [comment]
@kariminf A smart solution, I will test it in my side

**Pull request merged**
